In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
import codecs

In [37]:
data_dir = 'quot_mbnnews_2019_u.txt'
data_df = pd.read_csv(data_dir, encoding='utf-8')
data_df.head()

,MBN_MDA_SP_CD,MBN_ART_ESSN_NO,MDA_CGR_NM,STD_YEAR,ART_SJ_CN,ART_CN,ATCH_IMG_NM,JRNL_NM,WRT_DATE,QUOT_ID,...,QUOT_INST_NM,QUOT_AREA_NM,QUOT_GD_NM,QUOT_QY,QUOT_EVT,QUOT_DT,QUOT_TIME,QUOT_ANM,QUOT_PLNT,QUOT_AF
0,MBN,1201343,mbn00009,20190101,김주하 앵커가 전하는 1월 1일 뉴스8 주요뉴스,▶ '황금돼지 해' 밝아…해맞이 인파 북적\n 60년 만에 찾아온 황금돼지의 해가...,NaN,NaN,20190101194313,1201343-0,...,NaN,"한반도, 북한",신년##생활/건강#문구/사무용품#팬시용품,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,MBN,1201350,mbn00006,20190101,"청와대 ""한반도 문제 해결에 긍정적""…문 대통령, 해돋이 산행",【 앵커멘트 】\n 청와대는 김정은 위원장의 신년사에 대해 한반도 문제 해결에 긍...,NaN,최중락,20190101201701,1201350-0,...,NaN,"북미, 남북",신년##생활/건강#문구/사무용품#팬시용품,NaN,NaN,NaN,NaN,NaN,NaN,청와대
2,MBN,1201350,mbn00006,20190101,"청와대 ""한반도 문제 해결에 긍정적""…문 대통령, 해돋이 산행",【 앵커멘트 】\n 청와대는 김정은 위원장의 신년사에 대해 한반도 문제 해결에 긍...,NaN,최중락,20190101201701,1201350-1,...,NaN,한반,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MBN,1201350,mbn00006,20190101,"청와대 ""한반도 문제 해결에 긍정적""…문 대통령, 해돋이 산행",【 앵커멘트 】\n 청와대는 김정은 위원장의 신년사에 대해 한반도 문제 해결에 긍...,NaN,최중락,20190101201701,1201350-2,...,NaN,NaN,신년##생활/건강#문구/사무용품#팬시용품,NaN,NaN,NaN,한분 한분,NaN,NaN,NaN
4,MBN,1201355,mbn00009,20190101,김주하의 1월 1일 뉴스초점-누구 위한 위원회인가?,"지금 현재, 정부의 자문을 하는 위원회가 몇 개나 되는지 아십니까? \n \n ...",NaN,NaN,20190101204011,1201355-0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
def _get_econ(data_df):
    data_econ = data_df[ data_df['MDA_CGR_NM']=='mbn00003']
    
    return data_econ

In [4]:
## 2013 ~ 2019 7개년 데이터 전체 load

data_df = None

for year in range(13, 20):
    data_dir = 'analyzed_mbnnews_20' + str(year) + '.txt'
    print(data_dir)
    
    if data_df is None:
        data_df = pd.read_csv(data_dir, encoding='utf-8')
        data_econ = _get_econ(data_df)
    else:
        data_df_add = pd.read_csv(data_dir, encoding='utf-8')
        data_econ_add = _get_econ(data_df_add)
        data_econ = pd.concat([data_econ, data_econ_add])

analyzed_mbnnews_2013.txt
analyzed_mbnnews_2014.txt
analyzed_mbnnews_2015.txt
analyzed_mbnnews_2016.txt
analyzed_mbnnews_2017.txt
analyzed_mbnnews_2018.txt
analyzed_mbnnews_2019.txt

In [5]:
data_econ.describe()

       MBN_ART_ESSN_NO      STD_YEAR  ATCH_IMG_NM
count     7.648000e+03  7.648000e+03          0.0
mean      1.137862e+06  2.016328e+07          NaN
std       5.053103e+04  1.766080e+04          NaN
min       1.058613e+06  2.013112e+07          NaN
25%       1.092680e+06  2.015032e+07          NaN
50%       1.134710e+06  2.016082e+07          NaN
75%       1.182927e+06  2.018051e+07          NaN
max       1.228239e+06  2.019112e+07          NaN

In [6]:
data_econ

,MBN_MDA_SP_CD,MBN_ART_ESSN_NO,MDA_CGR_NM,STD_YEAR,ART_SJ_CN,ART_CN,ATCH_IMG_NM,JRNL_NM,WRT_DATE,ART_POSA,...,ART_INST_NM,ART_AREA_NM,ART_GD_NM,ART_QY,ART_EVT,ART_DT,ART_TIME,ART_ANM,ART_PLNT,ART_AF
9367,MBN,1058613,mbn00003,20131122,새벽부터 긴 줄…'발열내의' 열풍,【 앵커멘트 】\n 젊은층에게 외면받던 내의가 요즘은 반대로 패션 아이템으로 떠오...,NaN,정설민,20131122203148,"새벽/NNG, 부터/JX, 긴/VA, 줄/NNG, …/SE, '/SS, 발열/NNG...",...,"강남, MBN뉴스, 대형마트","서울, 경기, 김포시, 상도동","패션##패션잡화#주얼리#주얼리세트, 인터뷰##디지털/가전#음향가전#마이크, 아이##...","한 의류, 500만 장, 절반 이상, 2배 이상, 500명분, 275억 원",NaN,"올해, 지난해","새벽 6시, 15분 만",NaN,NaN,NaN
9371,MBN,1058617,mbn00003,20131122,'쏘나타' 미국에서 사면 더 쌀까?,【 앵커멘트 】\n 흔히 우리나라 자동차는 미국에서 사면 훨씬 싸게 살 수 있다고...,NaN,최은미,20131122203835,"'/SS, 쏘나타/NNG, '/SS, 미국/NNP, 에서/JKB, 사/VV, 면/E...",...,미국,"미국, 한국","수가##식품#축산#축산가공식품, 주코##디지털/가전#계절가전#가습기, 자동차##디지...","2만 2천여 달러, 1천990만 원, 100~400만 원, 270만 원, 3만 9백...",NaN,NaN,NaN,NaN,NaN,"미국 LA, 자동차"
9372,MBN,1058618,mbn00003,20131122,물 건너온 수입품은 왜 항상 비싼가?,【 앵커멘트 】\n 수입품 가격의 거품 논란이 거셉니다.\n 현지보다 두 세배는...,NaN,김태일,20131122204053,"물/NNG, 건너온/VV, 수입품/NNG, 은/JX, 왜/MAG, 항상/MAG, 비...",...,이탈리아산 원두커피,"미국, 경기, 용인시","스탠##패션잡화#신발#운동화, 과도##생활/건강#주방용품#조리기구, 인터뷰##디지털...","39,000원, 두 배, 두 세배, 4단계, 9,300원, 3만 원, 30%, 7배...",NaN,NaN,NaN,NaN,NaN,NaN
9373,MBN,1058619,mbn00003,20131122,"분양 '들썩', 매매는 '주춤'…부동산 '온도 차'",【 앵커멘트 】\n 올해 막바지 아파트 분양시장에 훈풍이 불고 있습니다.\n 그...,NaN,신동규,20131122204150,"분양/NNG, '/SS, 들썩/MAG, '/SS, ,/SP, 매매/NNG, 는/JX...",...,MBN 뉴스,"평촌신도시, 송파, 강남, 평촌, 관양동","수가##식품#축산#축산가공식품, 대한##디지털/가전#PC액세서리#USB액세서리, 보...","18대 1과, 두 곳, 12주, 7.3대 1, 3.6배, 0.02%",NaN,"올해, 20년 만",NaN,NaN,NaN,희비
9390,MBN,1058650,mbn00003,20131123,본점 직원 90억 횡령 적발…'나사 풀린' 국민은행,【 앵커멘트 】\n KB 국민은행 직원이 수십억 원대의 정부 기금을 횡령한 사실이...,NaN,이상범,20131123204227,"본점/NNG, 직원/NNG, 90/SN, 억/NR, 횡령/NNG, 적발/NNG, …...",...,"KB국민은행, KB 국민은행, 국민은행","일본, 서울, 도쿄","들통##생활/건강#주방용품#조리기구, 인터뷰##디지털/가전#음향가전#마이크, 나사#...","수십억 원, 1천7백억 원대, 50억 원, 90억 원, 90억 횡",NaN,2009년 1월,NaN,NaN,NaN,남대문로
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8378,MBN,1228191,mbn00003,20191116,"""선이 사라진다""…무선 시대 본격화",【 앵커멘트 】\n 거추장스러운 '선'이 사라지고 있습니다. \n 이미 대중화...,NaN,차민아,20191116202401,"""/SS, 선/NNG, 이/JKS, 사라진/VV, 다/EC, ""/SS, …/SE, ...",...,NaN,NaN,"공기청정기##디지털/가전#계절가전#공기정화기, 자동차##디지털/가전#태블릿PC/노트...",1억대,NaN,1년 내내,NaN,NaN,NaN,"자율주행차, 지하철, 전기차, 자동차"
8379,MBN,1228192,mbn00003,20191116,"일본, 액체 불화수소 수출 허가…""WTO 분쟁 고려한 듯""",【 앵커멘트 】\n 일본 정부가 우리나라에 대한 3가지 핵심 소재에 대한 수출 규...,NaN,이동훈,20191116202713,"일본/NNP, ,/SP, 액체/NNG, 불화수소/NNG, 수출/NNG, 허가/NNG...",...,"WTO, 스텔라케미파, 일본, 일본 정부, 삼성전자, 한일 군사정보보호협정, SK하이닉스","일본, 한국","스마트##스포츠/레저#자전거#자전거/MTB, 대한##디지털/가전#PC액세서리#USB...","3가지, 두개",한일 2차 양자협의와,"90일, 9월, 8월, 지난 7월",NaN,NaN,NaN,WTO
8385,MBN,1228220,mbn00003,20191117,"일본 ""수출규제 철회 없다"" 미국에 입장 전달",【 앵커멘트 】\n 일본이 지소미아 연장을 위해 수출규제를 철회할 생각이 없다는 ...,NaN,이무형,20191117194021,"일본/NNP, ""/SS, 수출/NNG, 규제/NNG, 철회/NNG, 없/VA, 다/...",...,"일본, 요미우리신문, 일본 정부, MBN뉴스, 세계무역기구 WTO","미국, 일본, 스위스, 제네바, 지소미아, 한국","세계##디지털/가전#생활가전#청소기, 대한##디지털/가전#PC액세서리#USB액세서리...","마지막, 2차, 1차, 3개",NaN,"지난 15일, 오는 19일",NaN,NaN,NaN,NaN
8400,MBN,1228238,mbn00003,20191117,현대차 빼고 10대 그룹 '최악 부진'…영업이익 19조 줄었다,【 앵커멘트 】 \n 우리나라 주요 그룹이 3분기 영업활동으로 벌어들인 이익이 지...,NaN,이상주,20191117204819,"현대차/NNP, 빼/VV, 고/EC, 10/SN, 대/NNB, 그룹/NNG, '/S...",...,"현대차, SK, LG, MBN뉴스, 삼성, 현대차 그룹",NaN,"세계##디지털/가전#생활가전#청소기, 유가##식품#가공식품#과자, 인터뷰##디지털/...","10대, 19조 원, 75%, 3분기, 5분의 1, 10조 원, 19조, 90곳, 1%대",미중 무역,"올해, 지난해, 지난해 12월부터 올해 10월, 11개월, 3분기",NaN,NaN,NaN,NaN
8401,MBN,1228239,mbn00003,20191117,"대한항공기, 독일 공항서 접촉 사고…21시간 운항 지연",【 앵커멘트 】\n 인천에서 출발해 독일 프랑크푸르트 공항에 도착해 대기 중이던 ...,NaN,김문영,20191117210142,"대한/NNP, 항공기/NNG, ,/SP, 독일/NNP, 공항/NNG, 서/JKB, ...",...,"대한항공 KE, 독일, 대한항공","독일, 에어나미비아, 프랑크푸르트, 아프리카, 어나미비아, 인천, 나미비아","대한##디지털/가전#PC액세서리#USB액세서리, 에어##디지털/가전#계절가전#공기정...","905편, 260명, 10여 분, 1시간, 241명",NaN,"17일, 오늘","밤, 21시간, 새벽 2시 20분쯤",날개,NaN,"대한항공 여객기, 대한항공기, 항공기"

In [7]:
data_econ = data_econ.reset_index()
data_econ = data_econ.drop('index', axis=1)

In [8]:
data_econ

,MBN_MDA_SP_CD,MBN_ART_ESSN_NO,MDA_CGR_NM,STD_YEAR,ART_SJ_CN,ART_CN,ATCH_IMG_NM,JRNL_NM,WRT_DATE,ART_POSA,...,ART_INST_NM,ART_AREA_NM,ART_GD_NM,ART_QY,ART_EVT,ART_DT,ART_TIME,ART_ANM,ART_PLNT,ART_AF
0,MBN,1058613,mbn00003,20131122,새벽부터 긴 줄…'발열내의' 열풍,【 앵커멘트 】\n 젊은층에게 외면받던 내의가 요즘은 반대로 패션 아이템으로 떠오...,NaN,정설민,20131122203148,"새벽/NNG, 부터/JX, 긴/VA, 줄/NNG, …/SE, '/SS, 발열/NNG...",...,"강남, MBN뉴스, 대형마트","서울, 경기, 김포시, 상도동","패션##패션잡화#주얼리#주얼리세트, 인터뷰##디지털/가전#음향가전#마이크, 아이##...","한 의류, 500만 장, 절반 이상, 2배 이상, 500명분, 275억 원",NaN,"올해, 지난해","새벽 6시, 15분 만",NaN,NaN,NaN
1,MBN,1058617,mbn00003,20131122,'쏘나타' 미국에서 사면 더 쌀까?,【 앵커멘트 】\n 흔히 우리나라 자동차는 미국에서 사면 훨씬 싸게 살 수 있다고...,NaN,최은미,20131122203835,"'/SS, 쏘나타/NNG, '/SS, 미국/NNP, 에서/JKB, 사/VV, 면/E...",...,미국,"미국, 한국","수가##식품#축산#축산가공식품, 주코##디지털/가전#계절가전#가습기, 자동차##디지...","2만 2천여 달러, 1천990만 원, 100~400만 원, 270만 원, 3만 9백...",NaN,NaN,NaN,NaN,NaN,"미국 LA, 자동차"
2,MBN,1058618,mbn00003,20131122,물 건너온 수입품은 왜 항상 비싼가?,【 앵커멘트 】\n 수입품 가격의 거품 논란이 거셉니다.\n 현지보다 두 세배는...,NaN,김태일,20131122204053,"물/NNG, 건너온/VV, 수입품/NNG, 은/JX, 왜/MAG, 항상/MAG, 비...",...,이탈리아산 원두커피,"미국, 경기, 용인시","스탠##패션잡화#신발#운동화, 과도##생활/건강#주방용품#조리기구, 인터뷰##디지털...","39,000원, 두 배, 두 세배, 4단계, 9,300원, 3만 원, 30%, 7배...",NaN,NaN,NaN,NaN,NaN,NaN
3,MBN,1058619,mbn00003,20131122,"분양 '들썩', 매매는 '주춤'…부동산 '온도 차'",【 앵커멘트 】\n 올해 막바지 아파트 분양시장에 훈풍이 불고 있습니다.\n 그...,NaN,신동규,20131122204150,"분양/NNG, '/SS, 들썩/MAG, '/SS, ,/SP, 매매/NNG, 는/JX...",...,MBN 뉴스,"평촌신도시, 송파, 강남, 평촌, 관양동","수가##식품#축산#축산가공식품, 대한##디지털/가전#PC액세서리#USB액세서리, 보...","18대 1과, 두 곳, 12주, 7.3대 1, 3.6배, 0.02%",NaN,"올해, 20년 만",NaN,NaN,NaN,희비
4,MBN,1058650,mbn00003,20131123,본점 직원 90억 횡령 적발…'나사 풀린' 국민은행,【 앵커멘트 】\n KB 국민은행 직원이 수십억 원대의 정부 기금을 횡령한 사실이...,NaN,이상범,20131123204227,"본점/NNG, 직원/NNG, 90/SN, 억/NR, 횡령/NNG, 적발/NNG, …...",...,"KB국민은행, KB 국민은행, 국민은행","일본, 서울, 도쿄","들통##생활/건강#주방용품#조리기구, 인터뷰##디지털/가전#음향가전#마이크, 나사#...","수십억 원, 1천7백억 원대, 50억 원, 90억 원, 90억 횡",NaN,2009년 1월,NaN,NaN,NaN,남대문로
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7643,MBN,1228191,mbn00003,20191116,"""선이 사라진다""…무선 시대 본격화",【 앵커멘트 】\n 거추장스러운 '선'이 사라지고 있습니다. \n 이미 대중화...,NaN,차민아,20191116202401,"""/SS, 선/NNG, 이/JKS, 사라진/VV, 다/EC, ""/SS, …/SE, ...",...,NaN,NaN,"공기청정기##디지털/가전#계절가전#공기정화기, 자동차##디지털/가전#태블릿PC/노트...",1억대,NaN,1년 내내,NaN,NaN,NaN,"자율주행차, 지하철, 전기차, 자동차"
7644,MBN,1228192,mbn00003,20191116,"일본, 액체 불화수소 수출 허가…""WTO 분쟁 고려한 듯""",【 앵커멘트 】\n 일본 정부가 우리나라에 대한 3가지 핵심 소재에 대한 수출 규...,NaN,이동훈,20191116202713,"일본/NNP, ,/SP, 액체/NNG, 불화수소/NNG, 수출/NNG, 허가/NNG...",...,"WTO, 스텔라케미파, 일본, 일본 정부, 삼성전자, 한일 군사정보보호협정, SK하이닉스","일본, 한국","스마트##스포츠/레저#자전거#자전거/MTB, 대한##디지털/가전#PC액세서리#USB...","3가지, 두개",한일 2차 양자협의와,"90일, 9월, 8월, 지난 7월",NaN,NaN,NaN,WTO
7645,MBN,1228220,mbn00003,20191117,"일본 ""수출규제 철회 없다"" 미국에 입장 전달",【 앵커멘트 】\n 일본이 지소미아 연장을 위해 수출규제를 철회할 생각이 없다는 ...,NaN,이무형,20191117194021,"일본/NNP, ""/SS, 수출/NNG, 규제/NNG, 철회/NNG, 없/VA, 다/...",...,"일본, 요미우리신문, 일본 정부, MBN뉴스, 세계무역기구 WTO","미국, 일본, 스위스, 제네바, 지소미아, 한국","세계##디지털/가전#생활가전#청소기, 대한##디지털/가전#PC액세서리#USB액세서리...","마지막, 2차, 1차, 3개",NaN,"지난 15일, 오는 19일",NaN,NaN,NaN,NaN
7646,MBN,1228238,mbn00003,20191117,현대차 빼고 10대 그룹 '최악 부진'…영업이익 19조 줄었다,【 앵커멘트 】 \n 우리나라 주요 그룹이 3분기 영업활동으로 벌어들인 이익이 지...,NaN,이상주,20191117204819,"현대차/NNP, 빼/VV, 고/EC, 10/SN, 대/NNB, 그룹/NNG, '/S...",...,"현대차, SK, LG, MBN뉴스, 삼성, 현대차 그룹",NaN,"세계##디지털/가전#생활가전#청소기, 유가##식품#가공식품#과자, 인터뷰##디지털/...","10대, 19조 원, 75%, 3분기, 5분의 1, 10조 원, 19조, 90곳, 1%대",미중 무역,"올해, 지난해, 지난해 12월부터 올해 10월, 11개월, 3분기",NaN,NaN,NaN,NaN
7647,MBN,1228239,mbn00003,20191117,"대한항공기, 독일 공항서 접촉 사고…21시간 운항 지연",【 앵커멘트 】\n 인천에서 출발해 독일 프랑크푸르트 공항에 도착해 대기 중이던 ...,NaN,김문영,20191117210142,"대한/NNP, 항공기/NNG, ,/SP, 독일/NNP, 공항/NNG, 서/JKB, ...",...,"대한항공 KE, 독일, 대한항공","독일, 에어나미비아, 프랑크푸르트, 아프리카, 어나미비아, 인천, 나미비아","대한##디지털/가전#PC액세서리#USB액세서리, 에어##디지털/가전#계절가전#공기정...","905편, 260명, 10여 분, 1시간, 241명",NaN,"17일, 오늘","밤, 21시간, 새벽 2시 20분쯤",날개,NaN,"대한항공 여객기, 대한항공기, 항공기"

In [9]:
data_econ['ART_TAG'][0]

'새벽/NNDate\n발열내, 서울, 분들\n요소들, 상도동\n\n심적, 경기, 멘트\n\n외면\n내의\n요즘\n반대\n패션_아이템, 김포시\n\n내복\n모양\n\n내복\n\n대형, 내의\n기능성\n디자인\n눈길\n\n인터뷰\n정영지\n경기_김포시, 발열, 기념\n발열_내의, 절반\n발열_내의, 앵커, 내복, 의류, MBN, 내의\n\n2배, 매장\n\n개장_기념, 개장, 내의\n\n발열_내의, 요소\n겸비\n고객들, 심적\n편안\n\n500만_장_이상_판매, 사람\n\n500명\n물량\n개장_15분, 대형\n마트\n가격\n발열\n돌풍\n\n대형마트\n내복_매출_275억_원, 2배\n물량\n준비\n\n인터뷰\n조혜성\n대형, 전기료, 아이템\n\n중심\n기능성\n디자인\n발열_내의, 강남, 6시, 판매\n대란\n발열_내의, 고객\n\n전기료_인상, 패션, 정설민, 개장\n\n인터뷰\n조의렴\n서울_상도동, 500만, 발열\n열풍\n\n앵커멘트, 6시_서울, 서울\n의류매장, 인상\n발열\n돌풍\n\nMBN뉴스_정설민, 대형\n마트\n패션_MD, MD\n\n색상\n단순\n디자\n분들, 정설민\n\n새벽/NNDate\n6시_서울_강남, 내복_매출, 매출\n절반, 내의\n새벽/NNDate\n장사진\n\n정설민, 내의\n반값\n판매\n소식\n사람들, 275억'

In [10]:
data_econ['ART_POSA'][0]

'새벽/NNG, 부터/JX, 긴/VA, 줄/NNG, …/SE, \'/SS, 발열/NNG, 내/NNB, 의/JKG, \'/SS, 열풍/NNG, 【/SS, 앵커/NNG, 멘트/NNG, 】/SW, 젊/VA, 은/ETM, 층/NNG, 에게/JKB, 외면/NNG, 받/VV, 던/ETM, 내의/NNG, 가/JKS, 요즘/NNG, 은/JX, 반대/NNG, 로/JKB, 패션/NNG, 아이템/NNG, 으로/JKB, 떠오르/VV, 고/EC, 있/VX, 습니다/EF, ./SF, 그/MM, 중심/NNG, 에/JKB, 는/JX, 기능/NNG, 성/XSN, 과/JC, 디자인/NNG, 을/JKO, 살린/VV, 발열/NNG, 내의/NNG, 가/JKS, 있/VV, 는데요/EF, ./SF, 이/MM, 발열/NNG, 내의/NNG, 를/JKO, 사/VV, 려고/EC, 새벽/NNG, 부터/JX, 장사진/NNG, 을/JKO, 이룬/VV, 곳/NNG, 도/JX, 있/VV, 습니다/EF, ./SF, 정설민/NNG, 기자/NNG, 입/VCP, 니다/EF, ./SF, 【/SS, 기자/NNG, 】/SS, 새벽/NNG, 6/SN, 시/NNB, 서울/NNP, 강남/NNP, 의/JKG, 한/MM, 의류/NNG, 매장/NNG, ./SF, 개장/NNG, 기념/NNG, 으로/JKB, 발열/NNG, 내의/NNG, 를/JKO, 반값/NNG, 으로/JKB, 판매/NNG, 한/XSV, 다는/ETM, 소식/NNG, 에/JKB, 벌써/MAG, 부터/JX, 많/VA, 은/ETM, 사람/NNG, 들/XSN, 이/JKS, 줄/NNG, 을/JKO, 서/VV, 기다리/VV, 고/EC, 있/VX, 습니다/EF, ./SF, 문/NNG, 이/JKS, 열리/VV, 자/EC, 500/SN, 명/NNB, 분/XSN, 의/JKG, 물량/NNG, 은/JX, 개장/NNG, 15/SN, 분/NNB, 만/NNB, 에/JKB, 동/NNG, 이/JKS, 납/VV, 니다/EF, ./SF, ▶/SW, 인터뷰/NNG, :/SP, 조의렴/NNG, //SP, 서울/NNP, 상도동/NNP, -/SS, "/SS, 다른/MM, 것/NNB, 에/JKB, 비해/VV, 서/EC, 이런저런/MM, 기능/NNG, 이/JKS, 많이/MAG, 들어가/VV, 있/VX, 잖아요/EF, ./SF, 그래서/MAJ, 따뜻/XR, 한/XSA, 것/NNB, 같/VA, 다는/ETM, 심/NNG, 적/XSN, 인/VCP, 편안/NNG, 함/XSA, 도/JX, 있/VV, 고요/EF, ./SF, "/SS, 지난해/NNG, 500/SN, 만/NR, 장/NNB, 이상/NNG, 판매/NNG, 되/XSV, 며/EC, \'/SS, 대란/NNG, \'/SS, 까지/JX, 빚어졌/VV, 던/ETM, 이/MM, 발열/NNG, 내의/NNG, 는/JX, 기능/NNG, 성/XSN, 뿐/JX, 아니/VCN, 라/EC, 디자인/NNG, 에서/JKB, 젊/VA, 은/ETM, 층/NNG, 의/JKG, 눈길/NNG, 을/JKO, 끌/VV, 었/EP, 습니다/EF, ./SF, ▶/SW, 인터뷰/NNG, :/SP, 정영지/NNP, //SP, 경기/NNG, 김포시/NNP, -/SS, "/SS, 내복/NNG, 이/VCP, 라고/EC, 보/VV, 기/ETN, 에/JKB, 는/JX, 모양/NNG, 도/JX, 예쁘/VA, 잖아요/EF, ./SF, 그래서/MAJ, 내복/NNG, 같/VA, 지/EC, 도/JX, 않/VX, 고/EF, ./SF, "/SS, 대/NNG, 형/XSN, 마트/NNG, 도/JX, 저렴/XR, 한/XSA, 가격/NNG, 을/JKO, 내세워/VV, 발열/NNG, 내/NNB, 의/JKG, 돌풍/NNG, 을/JKO, 이끌/VV, 고/EC, 있/VX, 습니다/EF, ./SF, 이/MM, 대형마트/NNP, 의/JKG, 지난해/NNG, 내복/NNG, 매출/NNG, 275/SN, 억/NR, 원/NNB, 중/NNB, 절반/NNG, 이상/NNG, 을/JKO, 발열/NNG, 내의/NNG, 가/JKS, 벌어들였/VV, 습니다/EF, ./SF, 올해/NNG, 는/JX, 2/SN, 배/NNG, 이상/NNG, 많/VA, 은/ETM, 물량/NNG, 을/JKO, 준비/NNG, 하/XSV, 고/EC, 있/VX, 습니다/EF, ./SF, ▶/SW, 인터뷰/NNG, :/SP, 조혜성/NNP, //SP, 대/NNG, 형/XSN, 마트/NNG, 패션/NNG, MD/SL, -/SS, "/SS, 다양/NNG, 한/XSA, 색상/NNG, 과/JC, 단순/NNG, 한/XSA, 디자/NNG, 인/VCP, 등/NNB, 젊/VA, 은/ETM, 분/NNB, 들/XSN, 이/JKS, 좋아할/VV, 만/NNB, 한/XSA, 요소/NNG, 들/XSN, 이/JKS, 겸비/NNG, 되/XSV, 면서/EC, 젊/VA, 은/ETM, 고객/NNG, 들/XSN, 이/JKS, 많이/MAG, 찾/VV, 고/EC, 있/VX, 습니다/EF, ./SF, "/SS, 전기료/NNG, 인상/NNG, 과/JKB, 맞물리/VV, 며/EC, 발열/NNG, 내/NNB, 의/JKG, 돌풍/NNG, 은/JX, 계속/NNG, 될/XSV, 것/NNB, 으로/JKB, 보입/VV, 니다/EF, ./SF, MBN/SL, 뉴스/NNG, 정설민/NNG, 입/VCP, 니다/EF, ./SF'

In [24]:
sample = data_econ['ART_POSA'][0]
to_list = sample.split(',')
print(to_list[:10])

['새벽/NNG', ' 부터/JX', ' 긴/VA', ' 줄/NNG', ' …/SE', " '/SS", ' 발열/NNG', ' 내/NNB', ' 의/JKG', " '/SS"]

In [34]:
tag_list = ['NNG', 'NNP', 'NP', 'MAG', 'MAJ', 'JKS', 'VV', 'VA', 'IC', 'SN', 'SL']

res = [ tok.split('/')[0].strip() for tok in to_list if tok.split('/')[-1] in tag_list ]
print(res)

['새벽', '긴', '줄', '발열', '열풍', '앵커', '멘트', '젊', '층', '외면', '받', '내의', '가', '요즘', '반대', '패션', '아이템', '떠오르', '중심', '기능', '디자인', '살린', '발열', '내의', '가', '있', '발열', '내의', '사', '새벽', '장사진', '이룬', '곳', '있', '정설민', '기자', '기자', '새벽', '6', '서울', '강남', '의류', '매장', '개장', '기념', '발열', '내의', '반값', '판매', '소식', '벌써', '많', '사람', '이', '줄', '서', '기다리', '문', '이', '열리', '500', '물량', '개장', '15', '동', '이', '납', '인터뷰', '조의렴', '서울', '상도동', '비해', '기능', '이', '많이', '들어가', '그래서', '같', '심', '편안', '있', '지난해', '500', '이상', '판매', '대란', '빚어졌', '발열', '내의', '기능', '디자인', '젊', '층', '눈길', '끌', '인터뷰', '정영지', '경기', '김포시', '내복', '보', '모양', '예쁘', '그래서', '내복', '같', '대', '마트', '가격', '내세워', '발열', '돌풍', '이끌', '대형마트', '지난해', '내복', '매출', '275', '절반', '이상', '발열', '내의', '가', '벌어들였', '올해', '2', '배', '이상', '많', '물량', '준비', '인터뷰', '조혜성', '대', '마트', '패션', 'MD', '다양', '색상', '단순', '디자', '젊', '이', '좋아할', '요소', '이', '겸비', '젊', '고객', '이', '많이', '찾', '전기료', '인상', '맞물리', '발열', '돌풍', '계속', '보입', 'MBN', '뉴스', '정설민']

In [11]:
from khaiii import KhaiiiApi
api = KhaiiiApi()

In [73]:
def _posa_to_token(train_data, train=False):
    posa_to_token = []
    vocab = []
    tag_list = ['NNG', 'NNP', 'NP', 'MAG', 'MAJ', 'JKS', 'VV', 'VA', 'IC', 'SL']  ## to be modified

    for idx in range(len(train_data)):
        try:
            txt = train_data['ART_POSA'][idx]
            pos_lst = txt.split(',')
            tok_lst = [ pos.split('/')[0].strip() for pos in pos_lst if pos.split('/')[-1] in tag_list ]
            vocab.extend(tok_lst)
            
        except:
            vocab.append('.')
            token_lst.append('.')
            
        posa_to_token.append(tok_lst)
            
    #print(title_to_token[-10:])
    return posa_to_token, vocab

In [74]:
##

txt_to_tok, vocab = _posa_to_token(data_econ)
print( len(txt_to_tok), len(vocab) )

7648 1278154

In [75]:
c_vocab = Counter(vocab)
c_vocab.most_common(200)

[('이', 49726),
 ('가', 35038),
 ('기자', 20901),
 ('있', 13271),
 ('인터뷰', 12594),
 ('영상', 9814),
 ('뉴스', 7701),
 ('MBN', 7162),
 ('앵커', 7028),
 ('멘트', 6860),
 ('취재', 5621),
 ('없', 5526),
 ('편집', 5171),
 ('하', 4628),
 ('받', 4475),
 ('정부', 4226),
 ('서울', 3839),
 ('같', 3518),
 ('안', 3364),
 ('더', 3188),
 ('회장', 3033),
 ('시장', 2925),
 ('kr', 2921),
 ('co', 2914),
 ('mbn', 2912),
 ('많', 2826),
 ('되', 2763),
 ('사람', 2673),
 ('스탠딩', 2608),
 ('때', 2578),
 ('가격', 2401),
 ('기업', 2392),
 ('이상', 2371),
 ('해', 2348),
 ('업체', 2305),
 ('정도', 2197),
 ('보', 2194),
 ('지난', 2193),
 ('경제', 2163),
 ('이번', 2102),
 ('대한', 2086),
 ('넘', 2073),
 ('문제', 2020),
 ('많이', 1996),
 ('아파트', 1996),
 ('가능', 1958),
 ('하지만', 1944),
 ('좋', 1937),
 ('중국', 1923),
 ('보도', 1892),
 ('했', 1831),
 ('제품', 1825),
 ('상황', 1820),
 ('경우', 1806),
 ('곳', 1801),
 ('우리', 1771),
 ('국내', 1771),
 ('조사', 1771),
 ('한국', 1752),
 ('위해', 1752),
 ('오늘', 1735),
 ('일본', 1730),
 ('높', 1720),
 ('지난해', 1718),
 ('최근', 1702),
 ('시간', 1636),
 ('금융', 1631),
 ('일', 1623),
 ('달', 1604),
 ('전', 1598),
 ('배', 1584),
 ('또', 1565),
 ('관계자', 1557),
 ('지금', 1543),
 ('지역', 1540),
 ('미국', 1513),
 ('찾', 1512),
 ('늘', 1506),
 ('가장', 1505),
 ('내', 1476),
 ('돈', 1451),
 ('부동산', 1433),
 ('사고', 1429),
 ('대해', 1417),
 ('차', 1414),
 ('올해', 1398),
 ('소비자', 1398),
 ('대표', 1398),
 ('먹', 1387),
 ('말', 1385),
 ('큰', 1383),
 ('들', 1364),
 ('안전', 1343),
 ('대출', 1335),
 ('전망', 1335),
 ('가운데', 1331),
 ('생각', 1330),
 ('환자', 1321),
 ('시작', 1320),
 ('필요', 1319),
 ('확인', 1311),
 ('앞', 1310),
 ('나오', 1306),
 ('경기', 1297),
 ('정주영', 1283),
 ('은행', 1269),
 ('모두', 1265),
 ('차량', 1250),
 ('이렇', 1246),
 ('분양', 1243),
 ('신동규', 1242),
 ('집', 1240),
 ('사실', 1233),
 ('사용', 1222),
 ('세계', 1221),
 ('최대', 1217),
 ('우리나라', 1206),
 ('특히', 1204),
 ('발생', 1204),
 ('금리', 1199),
 ('판매', 1186),
 ('투자', 1186),
 ('주택', 1165),
 ('정보', 1163),
 ('회사', 1154),
 ('주', 1146),
 ('이후', 1144),
 ('기준', 1140),
 ('뒤', 1139),
 ('피해', 1135),
 ('우려', 1127),
 ('크', 1120),
 ('고객', 1104),
 ('결과', 1100),
 ('보입', 1097),
 ('통해', 1096),
 ('됐', 1091),
 ('계속', 1082),
 ('규모', 1079),
 ('거래', 1071),
 ('대책', 1065),
 ('인기', 1057),
 ('사업', 1042),
 ('대', 1041),
 ('사', 1033),
 ('그런데', 1031),
 ('된', 1025),
 ('밝혔', 1019),
 ('직접', 1018),
 ('직원', 1017),
 ('맞', 1017),
 ('김경기', 1015),
 ('줄', 1013),
 ('이용', 1004),
 ('국민', 1003),
 ('만들', 1001),
 ('카드', 1001),
 ('합', 999),
 ('관리', 998),
 ('수출', 998),
 ('알려', 996),
 ('메르스', 988),
 ('규제', 979),
 ('현장', 976),
 ('대통령', 965),
 ('잘', 963),
 ('관련', 961),
 ('오', 959),
 ('다시', 957),
 ('나', 954),
 ('못', 950),
 ('점', 934),
 ('될', 933),
 ('따라', 930),
 ('한', 928),
 ('함께', 922),
 ('값', 921),
 ('기술', 919),
 ('자동차', 909),
 ('예상', 908),
 ('보이', 903),
 ('알', 900),
 ('논란', 899),
 ('입장', 899),
 ('산업', 892),
 ('현재', 889),
 ('보험', 886),
 ('개발', 883),
 ('간', 881),
 ('일부', 874),
 ('하루', 874),
 ('부담', 873),
 ('계획', 865),
 ('처음', 864),
 ('할', 862),
 ('경영', 858),
 ('김', 854),
 ('손', 853),
 ('수준', 851),
 ('추가', 835)]

In [68]:
from collections import Counter

def _get_fin_vocab(vocab):
    fin_vocab = {}
    
    c_vocab = Counter(vocab)
    cnt = len(fin_vocab)
    for voca in c_vocab:
        if (voca != '.') and (c_vocab[voca] > 1):
            fin_vocab[voca] = cnt
            cnt += 1
            
    return fin_vocab

In [69]:
def _tok_to_idx(tok_plylst, fin_vocab):
    res_idx = []
    for tok in tok_plylst:
        if tok in fin_vocab:
            res_idx.append(fin_vocab[tok])
        else:
            pass
        
    return res_idx

In [76]:
##

fin_vocab = _get_fin_vocab(vocab)
print('fin voca #:', len(fin_vocab))

txt_to_idx = []

for article in txt_to_tok:
    res_idx = _tok_to_idx(article, fin_vocab)
    txt_to_idx.append(res_idx)

fin voca #: 26286

In [79]:
## build article - voca (sparse) matrix (as the source of tf-idf matrix)

def _preproc_for_csr(txt_to_idx, from_idx=0):
    user_lst = []
    vocab_lst = []

    for idx, title in enumerate(txt_to_idx[from_idx:]):
        uid = from_idx + idx
        uid_lst = []
        for tok in title:
            vocab_lst.append(tok)
            user_lst.append(uid)             

    return user_lst, vocab_lst

In [80]:
user_lst, vocab_lst = _preproc_for_csr(txt_to_idx)

rows = np.array(user_lst)
cols = np.array(vocab_lst)
data = np.ones(len(user_lst))
data.shape

(1260133,)

In [84]:
import scipy.sparse as sp

usr_itm_mat = sp.csr_matrix((data, (rows, cols)), shape=(len(txt_to_tok), len(fin_vocab)))
usr_itm_mat.shape

(7648, 26286)

In [85]:
from sklearn.feature_extraction.text import TfidfTransformer

def _build_tfidf_mat(usr_itm_mat):
    tfidf_trans = TfidfTransformer()
    tfidf_mat = tfidf_trans.fit_transform(usr_itm_mat)
    
    return tfidf_mat

In [86]:
tfidf_mat = _build_tfidf_mat(usr_itm_mat)

In [111]:
## calculate similarity between articles

from sklearn.metrics.pairwise import linear_kernel

def _get_sim_article(tfidf_mat, given, topn):
    res_sim = dict()
    most_sim_idx, most_diff_idx = list(), list()

    cos_sim = linear_kernel(tfidf_mat[given:given+1], tfidf_mat).flatten()

    for idx, sim in enumerate(cos_sim):
        if (sim < 1) and (sim > 0):
            res_sim[sim] = idx

    res_sorted = sorted(res_sim, reverse=True)
    most_sim = res_sorted[:topn]
    most_diff = res_sorted[-topn:]

    for item in most_sim:
        most_sim_idx.append(res_sim[item])
        
    for item in most_diff:
        most_diff_idx.append(res_sim[item])
        
    return most_sim_idx, most_diff_idx

In [112]:
##
tmp = 0

most_sim_lst, most_diff_lst = _get_sim_article(tfidf_mat, given=tmp, topn=10)

In [113]:
most_sim_lst

[7642, 2165, 2884, 2306, 2081, 6972, 74, 7641, 7246, 5460]

In [114]:
most_diff_lst

[2292, 5259, 2363, 2390, 2269, 6793, 3871, 685, 7638, 4913]

In [110]:
data_econ['ART_SJ_CN'][7642]

"유니클로 '공짜 내복' 꼼수마케팅 논란"

In [117]:
data_econ['ART_POSA'][2363]

"[/SS, 간추린/VV, 오늘/NNG, ]/SS, '/SS, 애플/NNP, 워치/NNG, '/SS, 한국/NNP, 출시/NNG, …/SE, 3/SN, 가지/NNB, 종류/NNG, 애플/NNP, 의/JKG, 첫/MM, 스마트/NNG, 손목시계/NNG, '/SS, 애플워치/NNP, '/SS, 가/JKS, 오늘/NNG, (/SS, 26/SN, 일/NNB, )/SS, 스테인리스/NNG, 재질/NNG, 의/JKG, '/SS, 일반/NNG, 형/XSN, '/SS, 과/JC, 알루/NNG, 미늄/NNG, 재질/NNG, 의/JKG, '/SS, 스포츠/NNG, '/SS, ,/SP, 18/SN, K/SL, 금장/NNG, 케이스/NNG, 로/JKB, 만들/VV, 어/EC, 진/VX, '/SS, 에디션/NNP, '/SS, 등/NNB, 3/SN, 종류/NNG, 로/JKB, 나왔/VV, 습니다/EF, ./SF"